### ISSUE TITLE
`save_mesh` works wrong with an empty file name

### ISSUE THREAD

**Issue by Maikenov** [nndt-team/nndt#185]
method should not compile on empty file path
![image](https://user-images.githubusercontent.com/94566019/201856140-e67ccd6d-a636-4ac8-ac48-709af3213481.png)

**Comment by KonstantinUshenin** [comment]
This method should work with an empty file name as the numpy do that, or it should fail.

**Comment by semyon-v-dot** [comment]
The method is throwing ValueError with empty or None filename now
